---
- name: install docker
  hosts: dev,prod
  become: yes

  tasks:
   - name: install packages
     apt:
       name:
        - docker.io
        - python3-docker
       state: present
       update_cache: yes

- name: build app
  hosts: dev
  become: yes

  tasks:
   - name: copy Dockerfile
     copy:
       src: ./dev/Dockerfile
       dest: /home/pcadm/Dockerfile
     
   - name: copy s3cfg
     copy:
       src: /home/pcadm/.s3cfg
       dest: /home/pcadm/.s3cfg
       
   # - name: Build dev image
   #   docker_image:
   #     build:
   #       path: /home/pcadm/
   #     name: dev-mvn-alpine  
   #     source: build        